import { APIGatewayProxyEvent, APIGatewayProxyResult } from 'aws-lambda';
import { BedrockService } from '../services/bedrock/bedrock-service';
import { CachedBedrockService } from '../services/bedrock/cached-bedrock-service';
import { RedisCache } from '../services/cache/redis-cache';
import { OpenSearchService } from '../services/search/opensearch-service';
import { RankingService } from '../services/search/ranking-service';

// Initialize services
const redisUrl = `redis://${process.env.REDIS_HOST || 'localhost'}:${process.env.REDIS_PORT || '6379'}`;
const region = process.env.AWS_REGION || 'us-east-1';

const cachedBedrock = new CachedBedrockService(region, redisUrl);

const openSearchService = new OpenSearchService({
  endpoint: process.env.OPENSEARCH_ENDPOINT || 'https://localhost:9200',
  region,
});

const rankingService = new RankingService();

interface SearchRequest {
  query: string;
  userId?: string;
  filters?: {
    topics?: string[];
    difficulty?: 'beginner' | 'intermediate' | 'advanced';
    publicationYear?: { min?: number; max?: number };
  };
  limit?: number;
  offset?: number;
}

interface SearchResult {
  bookId: string;
  title: string;
  author: string;
  relevanceScore: number;
  explanation: string;
  snippet: string;
  topics: string[];
  difficulty: string;
}

export const handler = async (
  event: APIGatewayProxyEvent
): Promise<APIGatewayProxyResult> => {
  try {
    // Parse request body
    const body: SearchRequest = JSON.parse(event.body || '{}');
    const { query, userId, filters, limit = 10, offset = 0 } = body;

    if (!query || query.trim().length === 0) {
      return {
        statusCode: 400,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
        body: JSON.stringify({
          error: 'Query parameter is required',
        }),
      };
    }

    console.log('Search request:', { query, userId, filters, limit, offset });

    // Generate embedding for the search query
    const startTime = Date.now();
    const queryEmbedding = await cachedBedrock.generateEmbedding(query);
    const embeddingTime = Date.now() - startTime;

    console.log(`Query embedding generated in ${embeddingTime}ms`);

    // Perform hybrid search in OpenSearch (vector + keyword)
    const searchStartTime = Date.now();
    const searchHits = await openSearchService.hybridSearch(
      'books',
      queryEmbedding,
      query,
      {
        k: limit + offset,
        minScore: 0.5,
        vectorWeight: 0.7,
        keywordWeight: 0.3,
        filters: filters as Record<string, any>,
      }
    );
    const searchTime = Date.now() - searchStartTime;

    console.log(`OpenSearch returned ${searchHits.length} results in ${searchTime}ms`);

    // Convert search hits to results
    let results: SearchResult[] = searchHits.map((hit) => ({
      bookId: hit._id,
      title: hit._source.title,
      author: hit._source.author,
      relevanceScore: hit._score,
      explanation: '', // Will be generated by AI
      snippet: hit._source.description?.substring(0, 200) || '',
      topics: hit._source.topics || [],
      difficulty: hit._source.difficulty || 'intermediate',
    }));

    // Re-rank based on user profile if userId provided
    if (userId) {
      // TODO: Fetch user profile from DynamoDB
      const userProfile = null; // Placeholder
      results = rankingService.reRankResults(results, userProfile);
    }

    // Apply pagination
    results = results.slice(offset, offset + limit);

    // Calculate total processing time
    const totalTime = Date.now() - startTime;

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({
        results,
        metadata: {
          query,
          total: results.length,
          limit,
          offset,
          processingTime: totalTime,
        },
      }),
    };
  } catch (error) {
    console.error('Search error:', error);

    return {
      statusCode: 500,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({
        error: 'Internal server error',
        message: error instanceof Error ? error.message : 'Unknown error',
      }),
    };
  }
};
